name: Build

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["main"]

jobs:
  posix-gcc-build:
    name: Posix-GCC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the parent repository
        uses: actions/checkout@v2
        with:
          ref: main
          repository: FreeRTOS/FreeRTOS
          submodules: 'recursive'
          fetch-depth: 1
          path: ./workspace
      - name: Checkout the current repository
        uses: actions/checkout@v2
        with:
          path: ./workspace/FreeRTOS/Source
      - name: Posix Build Checker
        run: |
              bash workspace/.github/scripts/posix_build_checker.sh workspace
      - name: Install lib pcap dev
        run: |
          sudo apt-get install libpcap-dev
      - name: Posix Network Build Checker
        run: |
          bash workspace/.github/scripts/posix_network_build_checker.sh workspace
